### ISSUE TITLE
PERMISSIONS several commands dont send noperm messages 

### ISSUE THREAD

**Issue by CrimsonDart** [pgfmc/plugins#104]

**Comment by bkiscool** [comment]
Which commands, and what does it say exactly? I think in the plugin yml we can define the no permission message

**Comment by CrimsonDart** [comment]
no it still half executes
if i use /nick then it still sets the nickname value in playerdata, but it doesnt _set_ it

**Comment by CrimsonDart** [comment]
# uh oh

**Comment by CrimsonDart** [comment]
#BIG LETTERS !!!!!!

**Comment by CrimsonDart** [comment]
actually nvm i was in op modd\e
