### ISSUE TITLE
Spawn protection - No claiming around spawn - Spawn moderation

### ISSUE THREAD

**Issue by bkiscool** [pgfmc/plugins#116]
**Describe the feature you'd like**
A way to keep spawn a good area for new players to explore while not hindering the experience in any way

**Additional context**
* No claiming at or near spawn (have pgfmc claim spawn or something)
* No building at or near spawn
* Having a spawn area built-in creative mode or something that clearly directs new players into the correct type of playstyle PGF is
* Maybe a couple of holograms or signs with the rules (no stealing/griefing, no cheating/hacking)
* List other ideas in this thread

This need to happen for next season!!!!! akljf;akdsjfa;sd

**Comment by CrimsonDart** [comment]
Hey i think we should build the next season's spawn soon (right now)

**Comment by bkiscool** [comment]
Yes definitely
