### ISSUE TITLE
Requests in the command menu don't go away

### ISSUE THREAD

**Issue by bkiscool** [pgfmc/plugins#12]
In the command menu, after accepting the request, the request doesn't disappear. This may be a RequesterAPI issue.

**Comment by bkiscool** [comment]
Is this fixed?

**Comment by CrimsonDart** [comment]
no, they dont even show up right now

**Comment by bkiscool** [comment]
I'll work on this soon

**Comment by CrimsonDart** [comment]
DONE! finally
