### ISSUE TITLE
Masterbook is just broken

### ISSUE THREAD

**Issue by bkiscool** [pgfmc/plugins#53]
id
![unknown](https://user-images.githubusercontent.com/33919755/150079630-553bc955-f02d-4696-b003-8fffd719c0cc.png)
![unknown](https://user-images.githubusercontent.com/33919755/150079634-4769fd5a-e462-40e7-a4ac-4b07219b3dc7.png)
![unknown](https://user-images.githubusercontent.com/33919755/150079638-6da82051-8fc7-40d5-9e37-6f088f5939a6.png)
k

**Comment by CrimsonDart** [comment]
ok fixed
