### ISSUE TITLE
PLAYERDATA add commands to more easily control PlayerData in-game

### ISSUE THREAD

**Issue by CrimsonDart** [pgfmc/plugins#64]

**Comment by bkiscool** [comment]
I do have /tag
It's a really bad way of giving a player a simple value
Can be used for manually linking a player's discord and stuff like that

**Comment by CrimsonDart** [comment]
i can only do this for simple stuff like strings in a way that would make sense
nothing complex like lists of course
unless....
we have a python interface? i know python has a method to convert from the toString output back into what its from

**Comment by CrimsonDart** [comment]
ok done
