### ISSUE TITLE
PLAYERDATA optimize RAM usage

### ISSUE THREAD

**Issue by CrimsonDart** [pgfmc/plugins#65]

**Comment by bkiscool** [comment]
See #63

**Comment by bkiscool** [comment]
Not that big of a deal right now because there aren't tons of people

If there's some easy things to optimize then do that, but if it's hard then we can wait

**Comment by CrimsonDart** [comment]
I think this should be an issue that we should fix 
+ this is more descriptive than #63 , so ye

**Comment by bkiscool** [comment]
My bad
