### ISSUE TITLE
Claiming shulkers is broken

### ISSUE THREAD

**Issue by bkiscool** [pgfmc/plugins#79]
![image](https://user-images.githubusercontent.com/33919755/151671102-818218a0-3062-43d3-b12f-2bd44fcfdd50.png)

I'm not sure what the problem is

**Comment by CrimsonDart** [comment]
that only happens with shulkers
idk why

**Comment by CrimsonDart** [comment]
im pretty sure this got fixed a while ago
its not been reported in a while
