### ISSUE TITLE
New players don't get permissions

### ISSUE THREAD

**Issue by bkiscool** [pgfmc/plugins#8]
I do not know the source of this issue

This could be from the permissions manager or playerdata

See pgfmc/Core#14 for permissions manager rework

**Comment by CrimsonDart** [comment]
is this still happening?

**Comment by bkiscool** [comment]
Yes this is still happening

**Comment by bkiscool** [comment]
Hopefully fixed!

**Comment by bkiscool** [comment]
CONFIRMED: FINALLY FIXED!!!!!!

**Comment by bkiscool** [comment]
Okay so this has been happening again

It didn't happen to McQween, but has to everyone after him

I'll try to manually reload the player in Bukkit somehow probably

**Comment by bkiscool** [comment]
Try PD inits

**Comment by bkiscool** [comment]
This is still a problem, I'm going to disable this part of Core and replace it with PEX until a tested fix works

**Comment by bkiscool** [comment]
PEX is now the permissions manager
